version: '3.7'
services:
  web:
    build: ./django_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project/:./django_project
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev