version: "2"
services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  django:
    image: quantumobile/rc-base:latest
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
    env_file: .env.dev.txt
    volumes:
      - ./:/django_project
    working_dir: /django_project
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt
                    && invoke run-local"
