version: "2"
services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  django:
    image: quantumobile/rc-base:latest
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
    env_file: .env.dev.txt
    volumes:
      - ./:/Django_project
    working_dir: /Django_project
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt
                    && invoke run-local"

  react:
    image: node:16.11
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - django