version: "2"
services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: django_project
      POSTGRES_PASSWORD: zyVIRs8rC91XwTA9

  django:
    image: quantumobile/rc-base:latest
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
    env_file: .env.dev.txt
    volumes:
      - ./:/django_project
    working_dir: /django_project
    links:
      - db:db
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python ./django_project/manage.py runserver 0.0.0.0:8000"