# Generated by Django 3.2.6 on 2021-09-02 08:57

from django.db import migrations, models


def welcome_func(apps, schema_editor):
    Artist = apps.get_model("web_app", "artist")
    for artist in Artist.objects.all():
        artist.welcome_str = f"Hi, {artist.name}!"
        artist.save()


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="welcome_str",
            field=models.CharField(default="Hi", max_length=100),
        ),
        migrations.RunPython(welcome_func)
    ]
