# Generated by Django 3.2.6 on 2021-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210920_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='welcome_str',
        ),
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='pseudonym',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='imgs/songs')),
                ('time_length_sec', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='artist.Artist')),
            ],
        ),
    ]
