# Generated by Django 3.2.6 on 2021-10-20 14:41

import artist.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0002_auto_20210920_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='welcome_str',
        ),
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[None], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='pseudonym',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=artist.models.get_artist_upload_path),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=artist.models.get_song_upload_path)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=artist.models.get_song_upload_path)),
                ('time_length_sec', models.IntegerField(blank=True, default=0)),
                ('authors', models.ManyToManyField(blank=True, default=[None], to='artist.Artist')),
            ],
        ),
    ]
