# Generated by Django 3.2.6 on 2021-10-01 11:02

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20210929_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=artist.models.get_artist_upload_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(blank=True, to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, upload_to=artist.models.get_song_upload_path),
        ),
    ]
