# Generated by Django 3.2.6 on 2022-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default='', max_length=22),
        ),
    ]
