# Generated by Django 3.2.6 on 2021-10-01 13:19

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20211001_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(blank=True, default=[None], to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=artist.models.get_song_upload_path),
        ),
    ]
