# Generated by Django 3.2.6 on 2021-10-03 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0006_auto_20211001_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
