# Generated by Django 3.2.6 on 2021-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_artist_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
