# Generated by Django 3.2.6 on 2021-10-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0008_artist_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[None], to=settings.AUTH_USER_MODEL),
        ),
    ]
