# Generated by Django 3.2.6 on 2021-10-06 07:49

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_alter_artist_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='media_file',
            field=models.FileField(blank=True, default=None, upload_to=artist.models.get_song_upload_path),
        ),
    ]
