# Generated by Django 3.2.6 on 2021-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='imgs')),
                ('desc', models.TextField()),
                ('welcome_str', models.CharField(default='Hi', max_length=100)),
            ],
        ),
    ]
